docs/code-of-conduct.md
Per the OSPO guidelines, this is optional, but I think it is a good idea.
The current guidelines and code of conduct require a steward, I am
volunteering.
=> docs: include code of conduct document

.clang-format, .gitignore, CMakeLists.txt, cmake/BuildMetadata.cmake, google/cloud/functions/CMakeLists.txt, google/cloud/functions/internal/build_info.cc.in, google/cloud/functions/internal/build_info.h, google/cloud/functions/internal/compiler_info.cc, google/cloud/functions/internal/compiler_info.h, google/cloud/functions/internal/compiler_info_test.cc, google/cloud/functions/internal/version_info.h, google/cloud/functions/internal/version_info.h.in, google/cloud/functions/version.cc, google/cloud/functions/version.h, google/cloud/functions/version_test.cc
Create a library and some unit tests. I am not certain we will want to
have these functions (versions, compiler info, etc.) but they are easy
to copy from `google-cloud-cpp` and they provide something to bootstrap
the CI system around.
=> feat: bootstrap CMake-based builds

.clang-tidy, .github/workflows/sanitize.yaml, google/cloud/functions/CMakeLists.txt, google/cloud/functions/internal/parse_options.cc, google/cloud/functions/internal/parse_options.h, google/cloud/functions/internal/parse_options_test.cc
Parses the command-line arguments for the framework, including any
environment variables. Supports the full Functions Framework contract,
but ignore the arguments that cannot be supported in C++ (not at
runtime), e.g., --target.
Fixes #24
=> feat: implement command-line parsing function

google/cloud/functions/CMakeLists.txt, google/cloud/functions/http_response.h, google/cloud/functions/internal/call_user_function.cc, google/cloud/functions/internal/call_user_function.h, google/cloud/functions/internal/call_user_function_test.cc, google/cloud/functions/internal/http_message_types.h, google/cloud/functions/internal/wrap_request.h, google/cloud/functions/internal/wrap_response.h
We want to hide the Boost.Beast data types from the application, so we
need to call user-functions by wrapping the HTTP request and then
unwrapping the HTTP response.
Part of the work for #14
=> feat: wrap and unwrap Boost.Beast messages

.github/workflows/build.yaml, .github/workflows/sanitize.yaml, .github/workflows/style.yaml
Rename the builds to make them easier to see in the UI. Split the
style-related jobs (clang-tidy, cmake-format, clang-format) to their own
workflow.
=> ci: refactor builds

google/cloud/functions/CMakeLists.txt, google/cloud/functions/internal/framework.cc, google/cloud/functions/internal/framework.h, google/cloud/functions/internal/framework_test.cc
Add `google::cloud::functions::Run()`, a function to implement simple
HTTP servers.
=> feat: initial version of the framework

.github/workflows/images.yaml, build_scripts/Dockerfile, build_scripts/README.md, build_scripts/vcpkg-overlays/portfile.cmake, build_scripts/vcpkg-overlays/vcpkg.json
Add a `Dockerfile` and some support to generate development and runtime
images to build and deploy applications based on the framework. The
tests are very minimal at this point, we just check that the images can
be created, we do not verify that they are useful in any way. Additional
tests will come in future PRs. We also will need some scripts to use
these images, and some integration tests, but we need to start
somewhere.
Part of the work for #17
=> feat: implement development and runtime images

.github/workflows/build.yaml, .github/workflows/install.yaml, .github/workflows/sanitize.yaml, .github/workflows/style.yaml
TIL: a bit more about how GitHub Actions caching works. On a perfect
match for the hashing key the cache is not updated. When the inputs to
the cache change you certainly want to update it, but maybe you want to
reuse the previous version to start with a partially warm cache.  That
is what `restore-keys` is for. Warms up the cache, even if the inputs
change, and then update with the result.
=> ci: use previous cache when vcpkg.json changes

.github/workflows/images.yaml, CMakeLists.txt, build_scripts/build-application.Dockerfile, build_scripts/cmake/CMakeLists.txt, build_scripts/vcpkg-overlays/portfile.cmake, examples/CMakeLists.txt, examples/hello_gcs/CMakeLists.txt, examples/hello_gcs/hello_gcs.cc, vcpkg.json
Fix the code to support applications that provide their own CMake file
for the code. This is needed for more complex functions that depend on
additional libraries or even third-party dependencies. Wrote an example
to showcase this use-case and updated the builds to compile this
example.
Fixes #21
=> feat: applications can provide their own CMake file

.github/workflows/install.yaml, google/cloud/functions/quickstart/vcpkg.json
Compiles the framework and quickstart using BUILD_SHARED_LIBS=ON.
Fixes #19
=> ci: add build to test shared libraries

google/cloud/functions/integration_tests/basic_integration_test.cc, google/cloud/functions/internal/call_user_function.cc, google/cloud/functions/internal/call_user_function_test.cc
The spec requires that `/favicon.ico` and `/robots.txt` be intercepted
by the framework. The application function should not be called, and 404
is returned instead.
Fixes #26
=> feat: intercept special targets

.github/workflows/install.yaml, build_scripts/vcpkg-overlays/vcpkg.json, google/cloud/functions/CMakeLists.txt, google/cloud/functions/internal/parse_cloud_event_json.cc, google/cloud/functions/internal/parse_cloud_event_json.h, google/cloud/functions/internal/parse_cloud_event_json_test.cc, google/cloud/functions/quickstart/vcpkg.json, vcpkg.json
Add function to parse a stringified JSON object into a
`functions::CloudEvent`.
Fixes #120
=> feat: parse CloudEvent from JSON

examples/hello_from_namespace/hello_from_namespace.cc, examples/hello_from_nested_namespace/hello_from_nested_namespace.cc, examples/hello_gcs/hello_gcs.cc, examples/hello_multiple_sources/hello_multiple_sources.cc, examples/hello_with_third_party/hello_with_third_party.cc, examples/hello_world/hello_world.cc
=> cleanup: avoid internal-only headers in examples

google/cloud/functions/CMakeLists.txt, google/cloud/functions/internal/framework.cc, google/cloud/functions/internal/framework.h, google/cloud/functions/internal/framework_test.cc, google/cloud/functions/internal/user_functions.h
Refactored some duplicate definitions of `UserHttpFunction` and implemented `functions_internal::Run()` for Cloud Events.
Fixes #119.
=> feat: implement Run() for Cloud Event handlers

.github/workflows/images.yaml, build_scripts/generate-wrapper.sh, build_scripts/vcpkg-overlays/portfile.cmake, examples/CMakeLists.txt, examples/hello_cloud_event/hello_cloud_event.cc
This adds support for Cloud Events in the build scripts, including the
new signature type (`cloudevent`). To test the scripts this also adds a
"Hello World"-type example.
Fixes #62 and fixes #63
=> feat(CloudEvent): support in build scripts

examples/CMakeLists.txt, examples/site/hello_world_http/hello_world_http.cc, examples/site_test.cc
Implement the `helloworld_http` example and fix `helloworld_get`. Seems
like I got confused when I was reading the examples for other languages.
=> feat: implement functions_helloworld_http example

build_scripts/build-application.Dockerfile
This reduces the number of layers in the image, and as each layer is
"saved" and "committed", the fewer layers the less I/O, the faster the
build process (and our CIs).
=> ci: speed up Docker script to build images

examples/CMakeLists.txt, examples/cloud_event_examples_test.cc, examples/http_examples_test.cc
We have some examples that are specific to the framework, and do not
follow the region tags or any other conventions from the cloud site.
These were not tested, now they are.
The GCS example needs an integration test, but we have not figured out
how to do that just yet.
=> cleanup: improve testing for non-site examples

build_scripts/Dockerfile, pack/buildpack/bin/build
Cache the framework in vcpkg-cache.
Also cleanup some debugging statements.
=> ci: speed up buildpack steps

.github/workflows/build.yaml, .github/workflows/coverage.yaml, .github/workflows/install.yaml, .github/workflows/sanitize.yaml, .github/workflows/style.yaml, vcpkg.json
It seems that the builders for GitHub actions get updated from time to
time. With a new vcpkg binary all the existing vcpkg binary caches
become invalid, but GitHub actions did not know that, and keeps trying
to use it.
Also, we can share the vcpkg cache across builds, so let's do that.
=> ci: include vcpkg in vcpkg cache hash

examples/CMakeLists.txt, examples/site/testing_http/CMakeLists.txt, examples/site/testing_http/http_integration_test.cc
The next test will receive a URL, and we do not have reasonably easy
ways to parse a URL.  None that can be put in an example anyway: we
could use a regexp, but they are brutally complicated.
=> refactor: use libcurl in HTTP testing examples

examples/CMakeLists.txt, examples/site/hello_world_pubsub/CMakeLists.txt, examples/site/hello_world_pubsub/hello_world_pubsub.cc, examples/site/hello_world_pubsub/vcpkg.json, examples/site/hello_world_storage/CMakeLists.txt, examples/site/hello_world_storage/hello_world_storage.cc, examples/site/hello_world_storage/vcpkg.json, vcpkg.json
These examples will be used to create testing examples, i.e., show our
users how to write unit, integration, and system tests.  In those, we
will want to capture the log output.
Part of the work for #101 and #104
=> refactor: use Boost.Log in some examples

examples/CMakeLists.txt, examples/site/hello_world_storage/hello_world_storage.cc, examples/site/testing_storage/CMakeLists.txt, examples/site/testing_storage/storage_unit_test.cc
=> feat: implement storage_unit_test example

examples/site/testing_pubsub/CMakeLists.txt, examples/site/testing_pubsub/pubsub_integration_server.cc, examples/site/testing_pubsub/pubsub_integration_test.cc
=> feat: implement pubsub_integration_test example

CHANGELOG.md, README.md, build_scripts/cmake/CMakeLists.txt, examples/CMakeLists.txt, examples/hello_gcs/CMakeLists.txt, examples/hello_with_third_party/CMakeLists.txt, examples/site/concepts_filesystem/CMakeLists.txt, examples/site/hello_world_pubsub/CMakeLists.txt, examples/site/hello_world_storage/CMakeLists.txt, examples/site/testing_http/CMakeLists.txt, examples/site/testing_pubsub/CMakeLists.txt, examples/site/testing_storage/CMakeLists.txt, examples/site/tips_gcp_apis/CMakeLists.txt, google/cloud/functions/CMakeLists.txt, google/cloud/functions/config.cmake.in, google/cloud/functions/integration_tests/CMakeLists.txt, google/cloud/functions/quickstart/CMakeLists.txt
Time to add the long verbiage describing what we will not break and what
is subject to change without notice.
Incidentally, this fixes #201 and fixes #59, related to #202
=> doc: clarify backwards compatibility guidelines

CHANGELOG.md
I need to write "how-to" guides to use the functions framework.
These would be substantially easier if the framework was a
vcpkg port, and that requires a new release.
=> chore: prepare for v0.3.0 release

.github/workflows/install.yaml, google/cloud/functions/quickstart/CMakeLists.txt, google/cloud/functions/quickstart/README.md, google/cloud/functions/quickstart/hello_function/hello_function.cc, google/cloud/functions/quickstart/quickstart.cc, google/cloud/functions/quickstart/vcpkg.json
=> doc: describe how to run a local server

.github/workflows/build.yaml, .github/workflows/coverage.yaml, .github/workflows/sanitize.yaml, .github/workflows/style.yaml
Move all the build output to `${{runner.temp}}`, seems wrong to dump
artifacts in the workspace where the code is. Specially since they give
us a nice directory to put this stuff into.
=> ci: move builds to {{runner.temp}}

.github/workflows/build.yaml, .github/workflows/coverage.yaml, .github/workflows/install.yaml, .github/workflows/sanitize.yaml, .github/workflows/style.yaml, ci/restore-vcpkg-from-cache.sh
One of the workflow definition files had a syntax error. Workflows with such problems
are ignored in PRs (unless they are a required action), so we missed it.
I was too aggressive sharing the cache files, resulting in unusable caches, the cache
would be downloaded, vcpkg would not be able to use any of the contents, and then
the cache is not refreshed because the key matches perfectly.
The coverage build was not uploading any useful data, it needs to run from the directory
where the source lives, and receive the binary directory as an arguments.
=> ci: fix CI script problems

README.md, examples/site/hello_world_pubsub/hello_world_pubsub.cc, examples/site/testing_pubsub/CMakeLists.txt, examples/site/testing_pubsub/README.md, examples/site/testing_pubsub/pubsub_system_test.cc
Adds an example showing how to perform system tests for Pub/Sub
triggered functions.
Fixes #103
=> feat: implement pubsub_system_test example

.github/workflows/style.yaml, CMakeLists.txt, cmake/FunctionsFrameworkCppHelpers.cmake, examples/CMakeLists.txt, examples/site/testing_http/CMakeLists.txt, examples/site/testing_pubsub/CMakeLists.txt, examples/site/testing_storage/CMakeLists.txt, google/cloud/functions/CMakeLists.txt, google/cloud/functions/integration_tests/CMakeLists.txt
This is turned off by default because package maintainers and casual
users (which may have a different compiler than we do) should not see
breakage due to warnings.
=> cleanup: support turning on -Wall and -Werror

.github/workflows/install.yaml
The point of these builds is to check `make install`, I am not sure why
I had vcpkg installed, as it was not used.
=> cleanup: no vcpkg needed in install builds

examples/site/testing_http/http_integration_test.cc, examples/site/testing_pubsub/pubsub_integration_test.cc, examples/site/testing_storage/storage_integration_test.cc, google/cloud/functions/integration_tests/basic_integration_test.cc, google/cloud/functions/integration_tests/cloud_event_integration_test.cc, google/cloud/functions/internal/parse_cloud_event_json.cc
Many of the integration tests were using the same port, which stopped us
from running them in parallel. Found while testing on Windows, but
affects Linux too.
=> test: fix integration test to run in parallel

examples/site/hello_world_pubsub/hello_world_pubsub.cc, google/cloud/functions/internal/parse_cloud_event_json.cc, google/cloud/functions/internal/parse_cloud_event_json_test.cc
I would not have noticed this, but MSVC (with the right warnings) did.
More fixes to get the code to compile on MSVC will be coming in future
PRs, but this is useful by itself.
=> fix: incorrect iterator access in base64 decoding

README.md, examples/site/howto_create_container/README.md, examples/site/howto_deploy_to_cloud_run/README.md
Also refactored the existing guide to create containers to make both
look similar.
Fixes #226. Part of the work for #202
=> doc: new guide to deploy on Cloud Run

README.md, examples/site/howto_deploy_cloud_event/README.md
=> doc: new guide to deploy Pub/Sub function to Cloud Run

.gitignore, examples/CMakeLists.txt, examples/site/testing_http/CMakeLists.txt, examples/site/testing_http/http_integration_test.cc, examples/site/testing_pubsub/pubsub_integration_test.cc, examples/site/testing_storage/storage_integration_test.cc, examples/site_test.cc, google/cloud/functions/CMakeLists.txt, google/cloud/functions/integration_tests/basic_integration_test.cc, google/cloud/functions/integration_tests/cloud_event_integration_test.cc, google/cloud/functions/internal/compiler_info_test.cc, google/cloud/functions/internal/framework_impl_test.cc, google/cloud/functions/internal/parse_options_test.cc, google/cloud/functions/internal/setenv.cc, google/cloud/functions/internal/setenv.h
Most of the problems were around `setenv()` and `getenv()`, which I
solved by writing a small wrappers. Kept `std::getenv()` in the
examples, because that is most familiar to C++ developers, had to turn
off warnings from MSVC about it though.
Avoid googletest regex because they are unsupported with MSVC
Fix executable paths in integration tests
=> feat: fix compilation problems on MSVC

examples/site/howto_local_development/README.md
Simplify the instructions a bit.
=> doc: this library is now published in vcpkg

examples/site/tips_gcp_apis/tips_gcp_apis.cc
Both examples need to show the same thing, there is precedent in that
golang also reuses that example.
Fixes #105
=> doc: the gcp_apis sample also works for pubsub_publish

build_scripts/Dockerfile, pack/builder.toml, pack/buildpack/bin/build, pack/buildpack/buildpack.toml
Use a custom triplet in vcpkg to only build the release version of our
dependencies. That makes for a faster build, as vcpkg builds both debug
and release by default, and a smaller binary cache (~80MiB vs. ~330MiB).
Fixes #244 helps with #172
=> feat: reduce build times and vcpkg binary cache size

examples/site_test.cc
This portion of the test was taking about 60s, which is simply too slow
for a unit test and/or the CI builds.
=> ci: remove very slow and not very useful unit test

examples/site/howto_local_development/README.md, examples/site/howto_local_development/local_server.cc
The command to bootstrap `vcpkg` was wrong. But more importantly, we did
not explain in detail what was the expected output and results from each
command. In some cases I added options to each command to reduce the
informational output.
I also simplified the test function, there is no need to have a clean
shutdown, and having that code there is distracting.
Fixes #258, fixes #257, fixes #256, and fixes #255
=> doc: improve local development how-to guide

.github/workflows/coverage.yaml
I do not know what I did wrong, but reverting the changes in #211 fixed the code coverage reports. 🤕
=> ci: restore code coverage results

build_scripts/pack.Dockerfile, ci/README.md, ci/build-examples.yaml, ci/generate-build-examples.sh, examples/README.md, examples/site/howto_create_container/README.md, examples/site/howto_deploy_cloud_event/README.md, examples/site/howto_deploy_to_cloud_run/README.md
Use pack v0.17.0 in the CI builds and the examples, this is the current
version and has slightly different syntax for some commands than what we
were showing customers in the how-to guides. Also, I think it makes
sense to run CI with the same version we use for the how-to guides.
=> chore: update to pack v0.17.0

ci/build-examples.yaml, ci/generate-build-examples.sh
This change reduces the number of images pushed to Google Container
Registry, and removes the images created during the build.
If the build crashes, the cleanup step does not get to run, so as early
as possible a background step (one that has no dependencies in the
build and always succeeds) finds any images older than 4 weeks and
deletes them.
=> ci: cleanup images created during builds

build_scripts/Dockerfile, ci/README.md, ci/build-examples.yaml, ci/generate-build-examples.sh, ci/pack/builder.toml, ci/pack/buildpack/bin/build, ci/pack/buildpack/bin/detect, ci/pack/buildpack/buildpack.toml, examples/README.md, examples/site/howto_create_container/README.md, examples/site/howto_deploy_cloud_event/README.md, examples/site/howto_deploy_to_cloud_run/README.md
In the CI builds we need to test how the *current* version of
`functions-framework-cpp` works with buildback builders. But users of
the framework can use the *released* version of
`functions-framework-cpp`, as this is the version they get for local
development too. This PR splits the two builders, using different images
and buildpacks for each.
Fixes #249
=> cleanup: split CI vs. developer builders

examples/site/hello_world_pubsub/hello_world_pubsub.cc, examples/site/hello_world_pubsub/vcpkg.json, examples/site/howto_deploy_cloud_event/README.md, examples/site/testing_pubsub/README.md, vcpkg.json
Use a simpler library to parse base64 strings, it claims to be not the
most efficient implementation, but seems better for example code. Also
fix some mistakes in the README file.
=> cleanup: simplify Pub/Sub hello world example

google/cloud/functions/CMakeLists.txt, google/cloud/functions/internal/parse_cloud_event_http.cc, google/cloud/functions/internal/parse_cloud_event_http_test.cc, google/cloud/functions/internal/parse_cloud_event_json.cc, google/cloud/functions/internal/parse_cloud_event_json_test.cc, google/cloud/functions/internal/parse_cloud_event_storage.cc, google/cloud/functions/internal/parse_cloud_event_storage.h, google/cloud/functions/internal/parse_cloud_event_storage_test.cc
At the moment there is no way to deliver storage notifications in
CloudEvent format for a function deployed in Cloud Run. This change adds
a shim to parse Pub/Sub messages created by storage notifications as if
they were storage events.
Part of the work for #100
=> feat: convert storage Pub/Sub events

examples/site/hello_world_get/hello_world_get.cc, examples/site/hello_world_get/vcpkg.json
It does not use the nlohmann::json library, so we can remove a few
things.
=> cleanup: remove cruft from hello_world_get

google/cloud/functions/integration_tests/basic_integration_test.cc, google/cloud/functions/integration_tests/cloud_event_integration_test.cc, google/cloud/functions/internal/call_user_function.cc
Log exceptions from the application using structured logging so they are
reported to the right places.
Fixes #275
=> feat: use structured logging for exceptions

examples/cloud_event_examples_test.cc, examples/http_examples_test.cc, examples/site/testing_http/http_integration_server.cc, examples/site/testing_http/http_unit_test.cc
Consistently use `#include <...>` in the examples. Less confusion about
when to use what, and from the target audience (users of the framework),
all the stuff we include is "external".
Fixes #281
=> cleanup: examples use angle brackets

examples/site_test.cc
It was getting harder to find the tests in this file, at about 500
lines I do not think it is worthwhile to split it, but keeping the tests
sorted alphabetically should help.
=> cleanup: sort the site_test file

cmake/BuildMetadata.cmake, google/cloud/functions/internal/build_info.cc.in
The function, configuration option, and output messages referenced
`google-cloud-cpp`.
=> cleanup: fix names for some CMake symbols

google/cloud/functions/internal/parse_cloud_event_json.cc
When parsing CloudEvents in JSON format the error message was a bit
obscure, it indicated that a field was missing, but not which one. This
is more readable in the common case.
=> feat: improve error message for CloudEvent

google/cloud/functions/integration_tests/basic_integration_test.cc, google/cloud/functions/integration_tests/cloud_event_conformance.cc, google/cloud/functions/integration_tests/cloud_event_handler.cc, google/cloud/functions/integration_tests/cloud_event_integration_test.cc, google/cloud/functions/integration_tests/echo_server.cc, google/cloud/functions/integration_tests/http_conformance.cc, google/cloud/functions/internal/framework_impl.cc
We were creating a thread to handle each request, and then promptly
blocking until the thread completed. With this change we leave the
thread running. Before accepting a new connection we cleanup the memory
resources for old sessions, not that they are that big. We block and
stop accepting requests if there are 64 sessions running, at that point
it is probably better to let the hosting environment (Cloud Run, Cloud
Functions, whatever) create new instances to handle the additional load.
Fixes #309
=> fix: actually handle sessions in parallel

.github/workflows/coverage.yaml
Also enable the legacy mapping tests, as the framework now passes them.
Fixes #306
=> ci: update to use v1.0.0 of the conformance tests

google/cloud/functions/framework.h, google/cloud/functions/integration_tests/cloud_event_conformance.cc, google/cloud/functions/integration_tests/cloud_event_handler.cc, google/cloud/functions/integration_tests/echo_server.cc, google/cloud/functions/integration_tests/http_conformance.cc, google/cloud/functions/internal/framework_impl.cc, google/cloud/functions/internal/framework_impl.h, google/cloud/functions/internal/framework_impl_test.cc
Application developers can use `functions::Function` as a wrapper for
their functions in unit and integration tests.  Note that we need to
change the buildpacks (in a separate repository) to completely support
this feature.
=> feat: support `functions::Function` in `Run()`

examples/site/bearer_token/bearer_token.cc, google/cloud/functions/framework.h, google/cloud/functions/http_request.h, google/cloud/functions/http_response.h
This PR addresses review comments after an automatic merge.
The auto-merge ~trap~feature was fully armed when @devjgm approved #340.
=> cleanup: address review comments

build_scripts/pack/build.in, build_scripts/pack/cloudbuild.yaml, ci/README.md, ci/build-examples.yaml, ci/generate-build-examples.sh, ci/pack/buildpack/bin/build, examples/README.md, examples/site/howto_offload_builder_creation/README.md, examples/site/testing_pubsub/README.md, pack/buildpack/bin/build
To validate the framework we create our own buildpack and use it to
build the examples. With this change the buildpack uses `GOOGLE_`
prefixes for the environment variables controlling its behavior, which
matches how the official buildpacks are controlled:
https://github.com/GoogleCloudPlatform/buildpacks#functions-framework-buildpacks
=> refactor: use `GOOGLE_` prefix in buildpack

.dockerignore
Add some directories that appear as part of local GCB builds, this
speeds up local testing of buildpacks and other Docker-based workflows.
=> chore: update .dockerignore file

ci/cloudbuild/build.sh, ci/cloudbuild/builds/check-api.sh
Use Docker BuildKit to create the build image. Rename the build image to
avoid conflicts with the images used in `google-cloud-cpp`, sometimes In
need to use both in my workstation, more or less at the same time.
=> ci: update GCB scripts to use BuildKit

release/cutting-a-release.md
Lots of reformatting, and move the instructions to update the API baseline until *after* the version bump, just like we do for `google-cloud-cpp`.
=> doc: update release instructions

ci/cloudbuild/builds/check-api.sh
When running in the CI systems updating the baseline has no effect. When
running locally we often want to just commit the updated baseline.
=> ci: update baseline on check-api failures

ci/build-examples.yaml, ci/generate-build-examples.sh, examples/site/hello_world_http/hello_world_http.cc, examples/site/hello_world_pubsub/hello_world_pubsub.cc, examples/site/hello_world_storage/hello_world_storage.cc, examples/site/howto_create_container/README.md, examples/site/howto_deploy_cloud_event/README.md, examples/site/howto_deploy_to_cloud_run/README.md, examples/site/howto_local_development/CMakeLists.txt, examples/site/howto_local_development/local_server.cc, examples/site/testing_http/http_integration_server.cc, examples/site/testing_http/http_unit_test.cc, examples/site/testing_pubsub/README.md, examples/site/testing_pubsub/pubsub_integration_server.cc, examples/site/testing_pubsub/pubsub_unit_test.cc, examples/site/testing_storage/README.md, examples/site/testing_storage/storage_integration_server.cc, examples/site/testing_storage/storage_unit_test.cc, examples/site_test.cc
Change the How-to guides and associated examples to use declarative configuration for the signature type.
=> doc: examples use declarative configuration 2/N

ci/build-examples.yaml, examples/site/concepts_after_response/concepts_after_response.cc, examples/site/concepts_after_timeout/concepts_after_timeout.cc, examples/site/concepts_filesystem/concepts_filesystem.cc, examples/site/concepts_request/concepts_request.cc, examples/site/concepts_stateless/concepts_stateless.cc, examples/site_test.cc
=> doc: examples use declarative configuration 3/N

ci/build-examples.yaml, ci/cloudbuild/cloudbuild.yaml, ci/generate-build-examples.sh
Simplify error handling in optional steps for the Google Cloud Build config files.
=> ci: use `allowFailure` for optional steps

.github/workflows/style.yaml
No need to use `| grep` as `git ls-files` can filter files too.
=> ci: simplify `git ls-files`

.github/workflows/build.yaml, .github/workflows/coverage.yaml, .github/workflows/sanitize.yaml, .github/workflows/style.yaml
Save the vcpkg cache immediately after it is generated. This makes the next run faster if there is an error compiling our code or running one of our tests.
=> ci: always save vcpkg cache

examples/site/howto_create_container/README.md, examples/site/howto_deploy_cloud_event/README.md, examples/site/howto_deploy_to_cloud_run/README.md, examples/site/testing_storage/README.md
The newest buildpacks don't compile the C++ examples. Probably an omission in the buildpack. Change the documents to use the correct version.
=> docs: use working buildpacks

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile
The most important step in the build (running the build!) was not configured.  I updated some tools and enabled GCS-based cache for vcpkg.
=> ci: make `check-api` build functional

examples/howto_use_legacy_code/README.md, examples/site/howto_create_container/README.md, examples/site/howto_deploy_cloud_event/README.md, examples/site/howto_deploy_to_cloud_run/README.md, examples/site/howto_local_development/README.md
From time-to-time we need to update the instructions in the development branch to match the next release. That may invalidate the instructions if they are used with older releases. Put a warning in the "How-to" guides to avoid the problem.
=> docs: ask customers to follow the released instructions

google/cloud/functions/CMakeLists.txt, google/cloud/functions/config.cmake.in
The project nlohmann_json is used in few files, but is not listed in CMakeLists.txt. It would be nice having it listed in the CMake file too.
Reference about nlogmann_json CMake target: https://json.nlohmann.me/integration/cmake/
Files using nlogmann_json:
- https://github.com/GoogleCloudPlatform/functions-framework-cpp/blob/main/google/cloud/functions/internal/parse_cloud_event_legacy.cc
- https://github.com/GoogleCloudPlatform/functions-framework-cpp/blob/main/google/cloud/functions/internal/parse_cloud_event_storage.cc
/cc @toge
=> fix: add `nlohmann_json` as required CMake target

.github/workflows/coverage.yaml
Recently codecov.io started requiring an explicit token.
=> ci: pass codecov token

ci/README.md, examples/README.md, examples/site/howto_deploy_cloud_event/README.md, examples/site/howto_deploy_to_cloud_run/README.md, examples/site/testing_pubsub/README.md, examples/site/testing_storage/README.md
=> doc: set gcloud project once in config
