GoogleCloudPlatform/functions-framework-cpp

.github/CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/functions-framework-cpp/12)
=> chore: changed CODEOWNERS to use a GitHub team

google/cloud/functions/CMakeLists.txt, google/cloud/functions/http_response.cc, google/cloud/functions/http_response.h, google/cloud/functions/http_response_test.cc, google/cloud/functions/internal/wrap_response.cc, google/cloud/functions/internal/wrap_response.h
=> feat: introduced HTTP response wrapper

.github/workflows/install.yaml, cmake/InstallHeaders.cmake, google/cloud/functions/CMakeLists.txt, google/cloud/functions/config.cmake.in, google/cloud/functions/config.pc.in, google/cloud/functions/quickstart/CMakeLists.txt, google/cloud/functions/quickstart/quickstart.cc, google/cloud/functions/quickstart/vcpkg.json
=> feat: implement and test `make install` rules

.actrc
`act` (https://github.com/nektos/act) is a tool to run GitHub Actions
locally. This just adds a configuration file to make it easier to invoke
this tool in our code.
=> ci: support local builds with act

.dockerignore, .github/workflows/images.yaml, build_scripts/Dockerfile, build_scripts/build-application.Dockerfile, build_scripts/cmake/CMakeLists.txt, build_scripts/generate-wrapper.sh, google/cloud/functions/integration_tests/hello_world/CMakeLists.txt, google/cloud/functions/integration_tests/hello_world/hello_world.cc, vcpkg.json
Create a docker "script" to compile the application code into a Docker
image suitable for Cloud Run.
Fixes #22 and fixes #17
=> feat: implement driver to create runtime images

.github/workflows/images.yaml, build_scripts/build-application.Dockerfile, examples/hello_with_third_party/CMakeLists.txt, examples/hello_with_third_party/hello_with_third_party.cc, examples/hello_with_third_party/vcpkg.json, vcpkg.json
Applications can inject their own `vcpkg.json` file if they want to
install additional dependencies.
Fixes #48
=> feat: support third-party dependencies

examples/README.md
=> doc: describe how to deploy to Cloud Run

.github/workflows/images.yaml, examples/CMakeLists.txt, examples/hello_multiple_sources/greeting.cc, examples/hello_multiple_sources/greeting.h, examples/hello_multiple_sources/hello_multiple_sources.cc
=> feat: an example with more than one source file

google/cloud/functions/integration_tests/basic_integration_test.cc
=> test: verify exceptions are logged

google/cloud/functions/integration_tests/basic_integration_test.cc, google/cloud/functions/integration_tests/echo_server.cc, google/cloud/functions/internal/framework.cc
=> test: verify stdout/stderr are flushed

google/cloud/functions/CMakeLists.txt, google/cloud/functions/cloud_event.h, google/cloud/functions/cloud_event_test.cc
=> feat: implement wrapper for CloudEvent

.github/workflows/install.yaml, build_scripts/vcpkg-overlays/vcpkg.json, google/cloud/functions/CMakeLists.txt, google/cloud/functions/cloud_event.cc, google/cloud/functions/cloud_event.h, google/cloud/functions/cloud_event_test.cc, google/cloud/functions/config.cmake.in, google/cloud/functions/quickstart/vcpkg.json, vcpkg.json
=> feat: set time in CloudEvent using string

google/cloud/functions/internal/parse_cloud_event_json.cc, google/cloud/functions/internal/parse_cloud_event_json.h, google/cloud/functions/internal/parse_cloud_event_json_test.cc
=> feat: parse Cloud Event batches from JSON array

google/cloud/functions/CMakeLists.txt, google/cloud/functions/internal/parse_cloud_event_http.cc, google/cloud/functions/internal/parse_cloud_event_http.h, google/cloud/functions/internal/parse_cloud_event_http_test.cc
=> feat: parse Cloud Event from HTTP binary format

google/cloud/functions/internal/parse_cloud_event_http.cc, google/cloud/functions/internal/parse_cloud_event_http.h, google/cloud/functions/internal/parse_cloud_event_http_test.cc
=> feat: parse Cloud Events from any valid HTTP message

google/cloud/functions/internal/call_user_function.cc, google/cloud/functions/internal/call_user_function.h, google/cloud/functions/internal/call_user_function_test.cc
=> feat: implement caller for Cloud Events

google/cloud/functions/integration_tests/CMakeLists.txt, google/cloud/functions/integration_tests/cloud_event_handler.cc, google/cloud/functions/integration_tests/cloud_event_integration_test.cc, vcpkg.json
=> feat(CloudEvent): implement integration test

.github/workflows/images.yaml, examples/CMakeLists.txt, examples/site/hello_world_get/hello_world_get.cc, examples/site/hello_world_get/vcpkg.json
Start a new directory for all the examples that will be extracted to the cloud site.
This fixes #72
=> doc: implement hello_world_get example

examples/CMakeLists.txt, examples/site/http_cors/http_cors.cc, examples/site/http_cors_auth/http_cors_auth.cc
=> doc: implement CORS examples

examples/CMakeLists.txt, examples/site/http_method/http_method.cc
=> feat: implement functions_http_method example

examples/CMakeLists.txt, examples/site/http_xml/http_xml.cc, examples/site/http_xml/vcpkg.json, vcpkg.json
=> feat: implement functions_http_xml example

.codecov.yml, .github/workflows/coverage.yaml
=> ci: configure code coverage build

.github/workflows/images.yaml, examples/CMakeLists.txt, examples/site/hello_world_pubsub/hello_world_pubsub.cc, examples/site/hello_world_pubsub/vcpkg.json, examples/site_test.cc
=> feat: implement helloworld_pubsub example

examples/CMakeLists.txt, examples/site/hello_world_storage/hello_world_storage.cc, examples/site/hello_world_storage/vcpkg.json, examples/site_test.cc
=> feat: implement helloworld_storage example

examples/CMakeLists.txt, examples/site/concepts_after_response/concepts_after_response.cc, examples/site/concepts_after_timeout/concepts_after_timeout.cc, examples/site/concepts_filesystem/CMakeLists.txt, examples/site/concepts_filesystem/concepts_filesystem.cc, examples/site/concepts_request/concepts_request.cc, examples/site/concepts_stateless/concepts_stateless.cc, examples/site/tips_scopes/tips_scopes.cc, examples/site_test.cc
These are the examples needed in:
https://cloud.google.com/functions/docs/concepts/exec
Fixes #69, fixes #98, fixes #68, fixes #66, and fixes #67
=> feat: implement execution environment examples

examples/CMakeLists.txt, examples/site/env_vars/env_vars.cc, examples/site_test.cc
Shows how to read an environment variable :shrug:
Fixes #70
=> feat: implement functions_env_vars example

examples/CMakeLists.txt, examples/site/tips_infinite_retries/tips_infinite_retries.cc, examples/site/tips_lazy_globals/tips_lazy_globals.cc, examples/site/tips_retry/tips_retry.cc, examples/site_test.cc
These examples are used in the "Best Practices" page(s):
https://cloud.google.com/functions/docs/bestpractices/tips
https://cloud.google.com/functions/docs/bestpractices/retries
Fixes #95, fixes #96, and fixes #97
=> feat: implement some "Best Practices" examples

pack/builder.toml, pack/buildpack/bin/build, pack/buildpack/bin/detect, pack/buildpack/buildpack.toml
Initial support to build functions using build packs.
=> feat: initial buildpacks for C++

.github/workflows/images.yaml, build_scripts/cmake/CMakeLists.txt, pack/buildpack/bin/build
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/functions-framework-cpp/169)
=> feat: enable vcpkg caching in buildpacks

.github/workflows/images.yaml
Save some time by building the example images in parallel.
=> ci: parallelize image tests

ci/build-examples.sh, ci/build-examples.yaml
The Google Cloud Build configuration is automatically generated, but the
generator was too repetitive.
=> ci: cleanup build scripts

.github/workflows/sanitize.yaml, examples/CMakeLists.txt, examples/site/tips_gcp_apis/CMakeLists.txt, examples/site/tips_gcp_apis/tips_gcp_apis.cc, examples/site/tips_gcp_apis/vcpkg.json, examples/site_test.cc
=> feat: implement tips_gcp_apis example

examples/CMakeLists.txt, examples/http_unit_test.cc
=> feat: implement http_unit_test example

google/cloud/functions/CMakeLists.txt, google/cloud/functions/framework.h, google/cloud/functions/integration_tests/basic_integration_test.cc, google/cloud/functions/integration_tests/cloud_event_handler.cc, google/cloud/functions/integration_tests/cloud_event_integration_test.cc, google/cloud/functions/integration_tests/echo_server.cc, google/cloud/functions/internal/call_user_function.cc, google/cloud/functions/internal/call_user_function.h, google/cloud/functions/internal/framework_impl.cc, google/cloud/functions/internal/framework_impl.h, google/cloud/functions/internal/framework_impl_test.cc, google/cloud/functions/quickstart/quickstart.cc, google/cloud/functions/user_functions.h
=> refactor: move Run() to public API

build_scripts/Dockerfile, build_scripts/generate-wrapper.sh, build_scripts/vcpkg-overlays/portfile.cmake, ci/build-examples.sh, ci/build-examples.yaml, pack/buildpack/bin/build
=> ci: use current version when testing buildpacks

examples/CMakeLists.txt, examples/http_integration_server.cc, examples/http_integration_test.cc
=> feat: implement http_integration_test example

examples/site/testing_http/http_integration_test.cc
=> feat: implement http_system_test example

examples/CMakeLists.txt, examples/site/testing_pubsub/CMakeLists.txt, examples/site/testing_pubsub/pubsub_unit_test.cc
=> feat: implement pubsub_unit_test example

examples/site/testing_storage/CMakeLists.txt, examples/site/testing_storage/storage_integration_server.cc, examples/site/testing_storage/storage_integration_test.cc
=> feat: implement storage_integration_test example

.github/workflows/build.yaml, .github/workflows/style.yaml
=> ci: rename builds to match other languages

ci/README.md, examples/README.md
The integration tests need a small number of resources in the test
project, this document describes how to set them up and verify they
work.
=> doc: describe how to setup integration tests

README.md
=> doc: more improvements to top-level README

google/cloud/functions/quickstart/README.md
=> doc: describe how to create a Docker image

examples/site/howto_create_container/README.md, examples/site/howto_deploy_cloud_event/README.md, examples/site/howto_deploy_to_cloud_run/README.md, examples/site/howto_local_development/README.md
I made another pass through the How-to guides, using a fresh VM,
which help me identify gaps in the pre-requisites. I also found
some broken links (shame).
=> doc: multiple fixes in How-to guides

ci/README.md, examples/CMakeLists.txt, examples/site/tutorial_cloud_bigtable/CMakeLists.txt, examples/site/tutorial_cloud_bigtable/tutorial_cloud_bigtable.cc, examples/site/tutorial_cloud_bigtable/vcpkg.json
=> feat: implement code for Cloud Bigtable tutorial

ci/README.md, examples/CMakeLists.txt, examples/site/tutorial_cloud_spanner/CMakeLists.txt, examples/site/tutorial_cloud_spanner/tutorial_cloud_spanner.cc, examples/site/tutorial_cloud_spanner/vcpkg.json
=> feat: implement code for Cloud Spanner tutorial

.github/workflows/build.yaml, .github/workflows/coverage.yaml, .github/workflows/sanitize.yaml, .github/workflows/style.yaml, build_scripts/Dockerfile, ci/build-examples.sh, ci/build-examples.yaml, pack/buildpack/bin/build
Update the YAML file to include new examples, I forgot to run the shell
script that generates it. This needs a new version of vcpkg, one that
includes `functions-framework-cpp`, so update that too.
=> chore: update cloud build script

ci/build-examples.yaml, ci/generate-build-examples.sh, examples/CMakeLists.txt, examples/site/pubsub_subscribe/pubsub_subscribe.cc, examples/site_test.cc
=> feat: implement pubsub_subscribe example

build_scripts/pack/cloudbuild.yaml, build_scripts/pack/generate-builder-for-project.sh, examples/site/howto_create_container/README.md, examples/site/howto_deploy_cloud_event/README.md, examples/site/howto_deploy_to_cloud_run/README.md, examples/site/howto_offload_builder_creation/README.md
=> feat: how-to guide using Cloud Build for builder

ci/build-examples.yaml, examples/CMakeLists.txt, examples/site/log_helloworld/log_helloworld.cc, examples/site/log_helloworld/vcpkg.json, examples/site_test.cc
=> feat: implement log_helloworld example

ci/README.md, examples/site/hello_world_storage/hello_world_storage.cc, examples/site/hello_world_storage/vcpkg.json, examples/site/testing_storage/CMakeLists.txt, examples/site/testing_storage/README.md, examples/site/testing_storage/storage_system_test.cc
=> feat: implement storage_system_test example

ci/build-examples.yaml, examples/CMakeLists.txt, examples/site/log_stackdriver/log_stackdriver.cc, examples/site/log_stackdriver/vcpkg.json, examples/site_test.cc
This shows how to receive stackdriver log events via Pub/Sub.
Fixes #92
=> feat: implement log_stackdriver example

ci/build-examples.yaml, examples/CMakeLists.txt, examples/site/bearer_token/CMakeLists.txt, examples/site/bearer_token/bearer_token.cc, examples/site/bearer_token/vcpkg.json, examples/site_test.cc
=> feat: implement bearer_token example

ci/build-examples.yaml, examples/CMakeLists.txt, examples/site/hello_world_error/hello_world_error.cc, examples/site/hello_world_error/vcpkg.json, examples/site_test.cc
=> feat: implement helloworld_error example

examples/site/hello_world_error/hello_world_error.cc
=> doc: fix comment post review

CMakeLists.txt, examples/CMakeLists.txt, examples/site/testing_pubsub/CMakeLists.txt, examples/site/testing_storage/CMakeLists.txt, examples/site_test.cc, google/cloud/functions/internal/base64_decode.cc
Caught these problems when trying to send a PR for vcpkg. I really need a CI build for MSVC.
=> fix: build problems with MSVC

ci/build-examples.yaml, examples/CMakeLists.txt, examples/site/http_form_data/CMakeLists.txt, examples/site/http_form_data/http_form_data.cc, examples/site/http_form_data/vcpkg.json, examples/site_test.cc, vcpkg.json
=> feat: write the http_form_data example

examples/site/http_form_data/http_form_data.cc, google/cloud/functions/http_request.h
Some applications may want to move the contents of a HttpRequest.
=> feat: more efficient access to HttpRequest data

.github/workflows/build.yaml, .github/workflows/coverage.yaml, .github/workflows/sanitize.yaml, .github/workflows/style.yaml, build_scripts/Dockerfile, build_scripts/pack/build.in, ci/pack/buildpack/bin/build, pack/buildpack/bin/build
Pick up the latest `google-cloud-cpp` and `functions-framework-cpp`
versions.
=> chore: update vcpkg version

CHANGELOG.md
=> doc: release notes for v1.1.0

ci/build-examples.yaml, examples/site/env_vars/env_vars.cc, examples/site/hello_world_error/hello_world_error.cc, examples/site/hello_world_get/hello_world_get.cc, examples/site/http_content/http_content.cc, examples/site/http_cors/http_cors.cc, examples/site/http_cors_auth/http_cors_auth.cc, examples/site/http_form_data/http_form_data.cc, examples/site/http_method/http_method.cc, examples/site/http_xml/http_xml.cc, examples/site/log_helloworld/log_helloworld.cc, examples/site_test.cc
=> doc: examples use declarative configuration 4/N

ci/build-examples.yaml, examples/site/bearer_token/bearer_token.cc, examples/site/log_stackdriver/log_stackdriver.cc, examples/site/pubsub_subscribe/pubsub_subscribe.cc, examples/site/tips_gcp_apis/tips_gcp_apis.cc, examples/site/tips_infinite_retries/tips_infinite_retries.cc, examples/site/tips_lazy_globals/tips_lazy_globals.cc, examples/site/tips_retry/tips_retry.cc, examples/site/tips_scopes/tips_scopes.cc, examples/site_test.cc
Part of the work for #345. Completes site_test.cc
=> doc: examples use declarative configuration 5/N

.github/trusted-contribution.yml
Copied from: https://github.com/googleapis/google-cloud-cpp/blob/main/.github/trusted-contribution.yml
=> ci: run builds on trusted contribution
